// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolApplicationCore.Data.Data;

namespace SchoolApplicationCoreApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ShoolApplicationCore.Domain.Domains.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e27dd8e-ef2d-450b-b12d-0f18f2ce7bff"),
                            BirthDate = new DateTime(1982, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Class = "SS III",
                            Name = "Ejechi Charles"
                        },
                        new
                        {
                            Id = new Guid("a0a530c5-4c4b-4fde-b35c-ef20a7b31554"),
                            BirthDate = new DateTime(2011, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Class = "SS II",
                            Name = "Emmanuel Okokon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
